version: 2
jobs:
  build:
    working_directory: ~/ci
    docker:
      - image: angeart/docker-image-gcc73-cmake3-with-boost
    steps:
      - checkout
      - run:
          name: prepare
          command: mkdir build
      - run:
          name: configure
          command: |
            cd build
            cmake .. -GNinja
      - run:
          name: build
          command: |
            cd build
            ninja sapphire
      - persist_to_workspace:
          root: .
          paths:
              - .
  test:
    working_directory: ~/ci
    docker:
      - image: angeart/docker-image-gcc73-cmake3-with-boost
    steps:
      - attach_workspace:
          at: .
      - run:
          name: build
          command: |
            cd build
            ninja sapphire_test
      - run:
          name: test
          command: |
            cd build
            ninja test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build