version: 2
jobs:
  build:
    working_directory: ~/ci
    docker:
      - image: angeart/docker-image-gcc73-cmake3-with-boost
    steps:
      - checkout
      - run:
          name: prepare
          command: |
            mkdir build
            cd build
      - run:
          name: where?
          command: pwd
      - run:
          name: configure
          command: cmake .. -GNinja
      - run:
          name: build
          command: ninja sapphire